# OraWorldRegen 設定ファイル
worlds:
  resources:
    multiverse-world-name: "resources"
    environment: NORMAL
    world-type: NORMAL
    seed: ""
    generator: ""
    enabled: true
    countdown-seconds: 300
    fallback-world: "world"
    schedules:
      - cron: "0 4 * * 0"   # 毎週日曜 AM4:00

settings:
  notify-at-seconds: [300, 120, 60, 30, 10, 5, 4, 3, 2, 1]
  timezone: "Asia/Tokyo"
  debug: false
